CREATE TABLE endereco
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    numero           VARCHAR(20)                              NOT NULL,
    complemento      VARCHAR(100),
    cep              VARCHAR(10)                             NOT NULL,
    bairro           VARCHAR(100)                             NOT NULL,
    municipio        VARCHAR(100)                             NOT NULL,
    estado           VARCHAR(100)                             NOT NULL,
    data_criacao     TIMESTAMP WITHOUT TIME ZONE,
    data_atualizacao TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_endereco PRIMARY KEY (id)
);