CREATE TABLE relatorio
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome        VARCHAR(100)                             NOT NULL,
    telefone    VARCHAR(30)                              NOT NULL,
    cpf         VARCHAR(14)                              NOT NULL,
    numero      VARCHAR(20)                              NOT NULL,
    complemento VARCHAR(100),
    cep         VARCHAR(10)                              NOT NULL,
    bairro      VARCHAR(100)                             NOT NULL,
    municipio   VARCHAR(100)                             NOT NULL,
    estado      VARCHAR(100)                             NOT NULL,
    CONSTRAINT pk_relatorio PRIMARY KEY (id)
);

ALTER TABLE relatorio
    ADD CONSTRAINT uc_relatorio_cpf UNIQUE (cpf);