global:
  scrape_interval: 5s
  
scrape_configs:
  - job_name: 'emiteai-backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['emiteai-backend:8080']
        labels:
          application: 'emiteai-backend'