server:
  port: 8081

spring:
  application:
      name: relatorio-api

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:emiteai-db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        show_sql: false
        format_sql: false
    open-in-view: false

  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USER:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}

app-properties:
  rabbitmq:
    relatorio:
      queue: relatorio