server:
  port: 8080

spring:
  application:
    name: emiteai-backend

  profiles:
    active: dev

  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USER:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}
    listener:
      simple:
        default-requeue-rejected: false

app-properties:
  rabbitmq:
    relatorio:
      queue: relatorio
    emiteai:
      queue: emiteai
    queue:
      dlq: queue-dlq
      dlx: queue-dlx
      parking-lot: queue-parking-lot


