spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost:5432}/emiteai-db
    username: postgres
    password: root

  jpa:
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        show_sql: false
        format_sql: false
    open-in-view: false